import "@/assets/scss/app.scss";
import Header from "@/layouts/global/header";
import { Toaster } from "@/components/ui/sonner";
import { Toaster as DefaultToaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Authentication",
  description: "Generated by Next.js",
};

import { getServerSession } from "next-auth/next";
import SessionProvider from "@/components/providers/session-provider";
import { authOptions } from "../api/auth/[...nextauth]/route";

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions)
  
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Header />
          <section vaul-drawer-wrapper="">
            <main className="relative flex min-h-screen flex-col bg-background">
              {children}
            </main>
          </section>
        </SessionProvider>

        <Toaster position="bottom-center" richColors />
        <DefaultToaster />
      </body>
    </html>
  );
}
